### ISSUE TITLE
Find Companion Plant for Testing

### ISSUE THREAD

**Issue by jasonplojo** [kamikitty/ResilientSmartGarden#39]

**Comment by Marinela-S** [comment]
Plants have already been purchased. Originally we were planning on basil and mint, but since it's winter and near the end of growing season the options were limited. We ended up getting parsley and cilantro for the demo, which will be planted on Monday December 11. Just forgot to check if they were companions. we have a total of 12 plants 6 cilantro and 6 parsley . They should fit more comfortably with each other in the planters than the way we had them over the summer
